# -*- coding: utf-8 -*-
"""TalentCheck_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gwai-64jB3YVGIjJW0tyatLlSU_B0QmJ
"""

!pip install openai pypdf -q

from google.colab import userdata

OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise ValueError("❌ API key not found in Colab Secrets")

OPENROUTER_API_KEY = OPENROUTER_API_KEY.strip()  # IMPORTANT FIX
from openai import OpenAI

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

from pypdf import PdfReader

def read_pdf(file):
    reader = PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text

def optimizer_agent(resume_text, jd_text):
    prompt = f"""
You are the Optimizer Agent for TalentCheck AI.

Return ONLY valid JSON:

{{
  "match_score": 0-100,
  "key_skills": ["skill1", "skill2"],
  "summary": "short explanation"
}}

RESUME:
{resume_text}

JOB DESCRIPTION:
{jd_text}
"""

    res = client.chat.completions.create(
        model="openai/gpt-oss-120b:free",
        messages=[{"role": "user", "content": prompt}]
    )

    return res.choices[0].message.content

def evaluator_agent(scorecard, resume_text):
    prompt = f"""
You are a strict technical auditor.

TASK:
Check for:
1. timeline errors
2. hallucinated skills
3. seniority mismatch

RULES:
- Be strict but factual
- Do NOT over-explain
- Do NOT add extra assumptions
- Ignore phone numbers or irrelevant text
- Focus only on resume content vs scorecard

OUTPUT FORMAT (VERY IMPORTANT):
If no issues:
PASS

If issues exist:
FAIL
- bullet 1
- bullet 2
- bullet 3

RESUME:
{resume_text}

SCORECARD:
{scorecard}
"""

    res = client.chat.completions.create(
        model="google/gemma-3-4b-it:free",
        messages=[{"role": "user", "content": prompt}]
    )

    return res.choices[0].message.content

def refine(resume_text, jd_text, max_iter=3):

    scorecard = optimizer_agent(resume_text, jd_text)

    for i in range(max_iter):

        result = evaluator_agent(scorecard, resume_text)

        if "PASS" in result:
            return {
                "verified_scorecard": scorecard,
                "status": "PASSED",
                "audit": result
            }

        # feedback loop
        scorecard = optimizer_agent(
            resume_text + "\nFEEDBACK:\n" + result,
            jd_text
        )

    return {
        "verified_scorecard": scorecard,
        "status": "FAILED_AFTER_RETRIES",
        "audit": result
    }

from google.colab import files

# =========================
# UPLOAD CV
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

resume_text = read_pdf(file_name)

# =========================
# USER INPUT JOB DESCRIPTION
# =========================
print("\n✍️ Paste Job Description below:\n")
jd_text = input("JD: ")

# =========================
# RUN PIPELINE
# =========================
result = refine(resume_text, jd_text)

print("\n================ RESULT ================\n")
print(result)